### PR TITLE
PIVX attribution

### PR DESCRIPTION
**Pull request by Iconoclasta**
See https://github.com/DAPSCoin/DAPSCoin/issues/3

### CODE REVIEW

**Comment by Iconoclasta** [comment]
Hey, I've been informed about some disagreement on your end in issue #5 and this PR's regards.
Just to be clear this is a standard OSS attribution practise, the intent isn't to intimidate you. On the contrary, as (parents) of your codebase we'll be observing you, and routing for your success.

I have reviewed this case more seriously and there are easy grounds for a DMCA takedown, for wich the standard praxis indeed mandates to open an Issue - no point in treating it like a threat. 

It nevertheless does seem you originally forked PIVX and expanded on it. 

Proof: https://github.com/DAPSCoin/DAPSCoin/search?q=fuzzbawls&unscoped_q=fuzzbawls

please get this done with before wasting any more of either of our time.

**Comment by CapricornCandy** [comment]
You have our team's direct contact details and we're talking to you there. Stop using our Github as an advertising platform. We informed Pivx (you) that your issue is being looked into and Arcadia Group is responsible for fixing it if they made mistakes.

**Comment by Iconoclasta** [comment]
@CapricornCandy that's is not how this works. There is a protocol to follow when flagging and pursuing copyright violations and I am following it. If the praxis offends your sensibility go ask github to change their policy.

**Comment by DAPS-Spock** [comment]
@Iconoclasta This issue has now been resolved as per the last 3 editions of the Copying file.

**Pull request closed without merging**
