### PR TITLE
Wallet: Increase 2FA from 6 digits to 8 digits

### PR DESCRIPTION
**Pull request by ALEEF02**
I believe this is necessary for a more secure wallet

### CODE REVIEW

**Comment by ALEEF02** [comment]
I've been asked to upload some screenshots, so here they are
image
image

**Comment by ALEEF02** [comment]
There were no updates about the approval of my issue on the month leading up to the 1.0.8.0 release. Is my pull still being considered, assuming that I resolve the conflicting file? I'm not going to spend time writing to a branch that will be discarded...

**Comment by lyricidal** [comment]
> There were no updates about the approval of my issue on the month leading up to the 1.0.8.0 release. Is my pull still being considered, assuming that I resolve the conflicting file? I'm not going to spend time writing to a branch that will be discarded...

Hey,

Nice work on this. The only question I have is the in regards to the handling of users that already 2FA enabled with the 6 digit codes. Will they be forced to disable and re-enable it? Aside from sorting a solution for that and the minor conflict, we will be looking to add it in in one of our next builds.

**Comment by ALEEF02** [comment]
> > There were no updates about the approval of my issue on the month leading up to the 1.0.8.0 release. Is my pull still being considered, assuming that I resolve the conflicting file? I'm not going to spend time writing to a branch that will be discarded...
> 
> Hey,
> 
> Nice work on this. The only question I have is in regards to the handling of users that already 2FA enabled with the 6 digit codes. Will they be forced to disable and re-enable it? Aside from sorting a solution for that and the minor conflict, we will be looking to add it in in one of our next builds.

So, seeing how TOTP works, existing users would either have to manually change the parameters in their authenticator to 8 digits OR if they have their key written down they can manually add it back to the authenticator with 8 digits OR (the least confusing method) would have to disable it on 1.0.8.0 and then re-enable it on the 8-digit release.

**Comment by ALEEF02** [comment]
Didn't know we were scrapping light mode... which would explain the conflicts. I will update accordingly
image

**Comment by lyricidal** [comment]
> > > There were no updates about the approval of my issue on the month leading up to the 1.0.8.0 release. Is my pull still being considered, assuming that I resolve the conflicting file? I'm not going to spend time writing to a branch that will be discarded...
> > 
> > 
> > Hey,
> > Nice work on this. The only question I have is in regards to the handling of users that already 2FA enabled with the 6 digit codes. Will they be forced to disable and re-enable it? Aside from sorting a solution for that and the minor conflict, we will be looking to add it in in one of our next builds.
> 
> So, seeing how TOTP works, existing users would either have to manually change the parameters in their authenticator to 8 digits OR if they have their key written down they can manually add it back to the authenticator with 8 digits OR (the least confusing method) would have to disable it on 1.0.8.0 and then re-enable it on the 8-digit release.

Makes sense, we can bring it to our test group as well and see if there are any other ideas, but I think the least confusing method will be the way to go. 

> Didn't know we were scrapping light mode... which would explain the conflicts. I will update accordingly
> image

Yes, a decision with went with on our upcoming Patch Release of v1.0.8.1 (#223)

Unfortunately since the Light Theme didn't really go so well with the Rebrand we've scrapped it for now. If we get enough requests/demand for it we can look at re-theming it again in the future. Thanks for the quick resolve.

**Review by lyricidal — APPROVED** [review]
Looks good. We can add the handling/solution for current 2FA users with 6 digit codes in a separate PR.

**Pull request merged**
